accessLog: {}

tracing:
  otlp:
    grpc:
      insecure: true
      endpoint: tempo:4317

log:
  level: INFO

api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
